spring:
  application:
    name: butel-service-cunsumer-ribbon
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
