server:
  port: 8080

com:
  channelsoft:
    test:
      name: dev
      age: 20
      description: 我是${com.channelsoft.test.name}

spring:
  datasource:
    url: jdbc:mysql://192.168.30.51:3306/butel_manage?useUnicode=true&amp;characterEncoding=UTF-8
    username: ucds
    password: ucds
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
    show-sql: true
